sudo: required

services:
        - docker

before_install:
        - docker build -t skippyhacker/docker-react -f Dockerfile.dev

script:
        - docker run -e CI=true skippyhacker/docker-react npm run test -- --coverage
